name: 'Deploy to AWS'

# **What it does**: Builds the Quire Publication and Deploys it to an AWS S3 Bucket
# **Why we have it**: To automate and simplify managing the publication
# **Who does it impact**: Public users

on:
  push:
    branches-ignore:
      - main

jobs:
  install-quire:
    name: 'Install and Setup Quire'
    runs-on: macos-11
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: '14.18.1'
      - name: 'Check Node Version'
        run: 'node --version'
      - name: 'Install Quire with npm'
        run: |
          npm install --global @thegetty/quire-cli
          quire --help